[project]
name = "claudit-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.93.0",
    "rich>=14.0.0",
    "tiktoken>=0.9.0",
]
